// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.TesisData.TesisModels
{
    public partial class Clienti
    {
        /// <summary>
        /// PK
        /// </summary>
        public decimal IdCliente { get; set; }
        /// <summary>
        /// Codice cliente generato progressivo
        /// </summary>
        public string CodCliente { get; set; }
        /// <summary>
        /// Ragione sociale
        /// </summary>
        public string RagioneSociale { get; set; }
        /// <summary>
        /// Indirizzo
        /// </summary>
        public string Indirizzo { get; set; }
        /// <summary>
        /// Località
        /// </summary>
        public string Localita { get; set; }
        /// <summary>
        /// Provincia
        /// </summary>
        public string Provincia { get; set; }
        /// <summary>
        /// Cap
        /// </summary>
        public string Cap { get; set; }
        /// <summary>
        /// Partita IVA
        /// </summary>
        public string PartitaIva { get; set; }
        /// <summary>
        /// Codice fiscale
        /// </summary>
        public string CodiceFiscale { get; set; }
        /// <summary>
        /// Telefono
        /// </summary>
        public string Telefono { get; set; }
        /// <summary>
        /// Fax
        /// </summary>
        public string Fax { get; set; }
        /// <summary>
        /// Indirizzo email
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// Indirizzo web
        /// </summary>
        public string Web { get; set; }
        /// <summary>
        /// Tipo cliente
        /// </summary>
        public string CodTipoCliente { get; set; }
        /// <summary>
        /// Centro di competenza assegnato
        /// </summary>
        public string CodCdc { get; set; }
        /// <summary>
        /// Nome interlocutore commerciale
        /// </summary>
        public string IntCom { get; set; }
        /// <summary>
        /// Nome interlocutore tecnico
        /// </summary>
        public string IntTec { get; set; }
        /// <summary>
        /// Note
        /// </summary>
        public string Note { get; set; }
        /// <summary>
        /// Codice di anagrafica esterna
        /// </summary>
        public string CodiceEsterno { get; set; }
        /// <summary>
        /// Gruppo clienti1
        /// </summary>
        public string CodGruppoClienti1 { get; set; }
        /// <summary>
        /// Gruppo clienti2
        /// </summary>
        public string CodGruppoClienti2 { get; set; }
        /// <summary>
        /// Gruppo clienti3
        /// </summary>
        public string CodGruppoClienti3 { get; set; }
        /// <summary>
        /// Area geografica
        /// </summary>
        public string CodAreaGeografica { get; set; }
        /// <summary>
        /// Regione
        /// </summary>
        public string CodRegione { get; set; }
        /// <summary>
        /// Nazione
        /// </summary>
        public string CodNazione { get; set; }
        /// <summary>
        /// Azienda assegnata
        /// </summary>
        public string CodAzienda { get; set; }
        /// <summary>
        /// FK TabTipoContratto
        /// </summary>
        public string CodTipoContratto { get; set; }
        /// <summary>
        /// Nome interlocutore
        /// </summary>
        public string MailInterlocutore { get; set; }
        /// <summary>
        /// Cliente visibile in gestione chiamate
        /// </summary>
        public bool? VisibileChiamate { get; set; }
        /// <summary>
        /// Se valido
        /// </summary>
        public bool Valido { get; set; }
        /// <summary>
        /// IdUtente inserimento
        /// </summary>
        public int? FirstUser { get; set; }
        /// <summary>
        /// IdUtente ultima modifica
        /// </summary>
        public int? LastUser { get; set; }
        /// <summary>
        /// Data inserimento
        /// </summary>
        public DateTime? FirstDate { get; set; }
        /// <summary>
        /// Data ultima modifica
        /// </summary>
        public DateTime? LastDate { get; set; }
        /// <summary>
        /// Timestamp ultima modifica
        /// </summary>
        public byte[] LastUp { get; set; }
        /// <summary>
        /// Mercato assegnato (FK TabMercato)
        /// </summary>
        public string Codmercato { get; set; }
        /// <summary>
        /// FK TabCreditoScaduto
        /// </summary>
        public string CodCreditoScaduto { get; set; }
        /// <summary>
        /// Eventuale importo insoluto
        /// </summary>
        public decimal? ImportoCreditoScaduto { get; set; }
        /// <summary>
        /// FK TabTipoFatturazione
        /// </summary>
        public string CodTipoFatturazione { get; set; }
        /// <summary>
        /// FK TabCondizioniPagamento
        /// </summary>
        public string CodCondizionePagamento { get; set; }
        /// <summary>
        /// Nome banca appoggio
        /// </summary>
        public string BancaAppoggio { get; set; }
        /// <summary>
        /// Numero CC banca
        /// </summary>
        public string BancaCc { get; set; }
        /// <summary>
        /// CAB
        /// </summary>
        public string BancaCab { get; set; }
        /// <summary>
        /// ABI
        /// </summary>
        public string BancaAbi { get; set; }
        /// <summary>
        /// CIN
        /// </summary>
        public string BancaCin { get; set; }
        /// <summary>
        /// IBAN
        /// </summary>
        public string CodiceIban { get; set; }
        /// <summary>
        /// Indirizzo mail amministrazione (per invio allegati)
        /// </summary>
        public string EmailAmministrazione { get; set; }
        /// <summary>
        /// Indica se suggerire invio mail al contatto in chiamata
        /// </summary>
        public bool? InviaMailContatto { get; set; }
        /// <summary>
        /// Indica se suggerire invio mail al ubicazione in chiamata
        /// </summary>
        public bool? InviaMailUbicazione { get; set; }
        /// <summary>
        /// Indica se suggerire invio mail a cliente in chiamata
        /// </summary>
        public bool? InviaMailCliente { get; set; }
        /// <summary>
        /// FK Listini. Listino applicato al cliente
        /// </summary>
        public long? IdListino { get; set; }
        /// <summary>
        /// FK TabRapportini (modello di rapportino da usare per il cliente)
        /// </summary>
        public string CodRapportino { get; set; }
        /// <summary>
        /// Se cliente soggetto a verifica chiamata (Tabellone controllo Tempi)
        /// </summary>
        public bool? ControlloChiamate { get; set; }
        /// <summary>
        /// Se inviare mail automatica con rapportino interenti
        /// </summary>
        public bool? MailRapportinoAutomatico { get; set; }
        /// <summary>
        /// Per quali Tipi attività (codici FK TabAttivita) effettuare invio automatico rapportino
        /// </summary>
        public string MailRapportinoAttivita { get; set; }
        /// <summary>
        /// Indirizzi mail destinatari rapportino automatico
        /// </summary>
        public string MailRapportinoDestinatario { get; set; }
        /// <summary>
        /// FK EmailAgent_Account
        /// </summary>
        public long? IdAccount { get; set; }
        public bool? TmnoMailRapportino { get; set; }
        /// <summary>
        /// FK TabAgenti
        /// </summary>
        public string CodAgente1 { get; set; }
        /// <summary>
        /// FK TabAgenti
        /// </summary>
        public string CodAgente3 { get; set; }
        /// <summary>
        /// FK TabAgenti
        /// </summary>
        public string CodAgente2 { get; set; }
        /// <summary>
        /// FK TabAgenti
        /// </summary>
        public string CodAgente4 { get; set; }
        /// <summary>
        /// FK TabCausaliFattura (se specificato, solo queste causali sono utilizzabili su chiamate del cliente)
        /// </summary>
        public string CausaliDiFatturazione { get; set; }
        /// <summary>
        /// Contatto Telefono dell&apos;interlocutore commerciale
        /// </summary>
        public string TelefonoIntCommerciale { get; set; }
        /// <summary>
        /// Contatto Fax dell&apos;interlocutore commerciale
        /// </summary>
        public string FaxIntCommerciale { get; set; }
        /// <summary>
        /// Contatto Email dell&apos;interlocutore commerciale
        /// </summary>
        public string EmailIntCommerciale { get; set; }
        public string FiltroAttivita { get; set; }
        public string FiltroTipoGuasto { get; set; }
        public string FiltroCatGuasto { get; set; }
        public string FiltroConoscenza { get; set; }
        public string FiltroTipoServizio { get; set; }
        public string FiltroGruppoUbicazioni1 { get; set; }
        public string FiltroGruppoUbicazioni2 { get; set; }
        public string FiltroGruppoUbicazioni3 { get; set; }
        public bool? Ccmail { get; set; }
        public string CodiceSms { get; set; }
        public bool? CalcolaTempiFornitore { get; set; }
        public bool? AttivaCampiObbligatoriHda { get; set; }
        public string DominioAgent { get; set; }
        public string Insegna { get; set; }
        public string CodiceUnivoco { get; set; }
        public int? FusoOrario { get; set; }
        public string FiltroEventiAssegnazione { get; set; }
        public string FiltroRisorseAssegnazione { get; set; }
    }
}