// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.TesisData.TesisModels
{
    public partial class TabCostruttore
    {
        /// <summary>
        /// Codice costruttore prodotto
        /// </summary>
        public string CodCostruttore { get; set; }
        /// <summary>
        /// Descrizione costruttore prodotto
        /// </summary>
        public string Descrizione { get; set; }
        public bool? Valido { get; set; }
        public int? FirstUser { get; set; }
        public int? LastUser { get; set; }
        public DateTime? FirstDate { get; set; }
        public DateTime? LastDate { get; set; }
        public byte[] Lastup { get; set; }
    }
}