// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.TesisData.TesisModels
{
    public partial class TabTrasportatori
    {
        public long IdTrasportatore { get; set; }
        public string Descrizione { get; set; }
        public long? Valido { get; set; }
        public long? FirstUser { get; set; }
        public DateTime? FirstDate { get; set; }
        public long? LastUser { get; set; }
        public DateTime? LastDate { get; set; }
        public byte[] Lastup { get; set; }
    }
}