// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class CausaleAnnullamento
    {
        public CausaleAnnullamento()
        {
            Shipment = new HashSet<Shipment>();
        }

        public string CausaleAnnullamentoId { get; set; }
        public string Descrizione { get; set; }
        public bool Valido { get; set; }
        public DateTime FirstDate { get; set; }
        public DateTime LastDate { get; set; }
        public int FirstUser { get; set; }
        public int LastUser { get; set; }

        public virtual ICollection<Shipment> Shipment { get; set; }
    }
}