// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class CausaleMovimentiMagazzino
    {
        public CausaleMovimentiMagazzino()
        {
            PurchaseOrder = new HashSet<PurchaseOrder>();
            Receiving = new HashSet<Receiving>();
            SalesOrder = new HashSet<SalesOrder>();
            Shipment = new HashSet<Shipment>();
        }

        public string CausaleMovimentiMagazzinoId { get; set; }
        public string Descrizione { get; set; }
        public bool IsCarico { get; set; }
        public bool IsScarico { get; set; }
        public int AnagraficaRichiesta { get; set; }
        public bool Valido { get; set; }
        public DateTime FirstDate { get; set; }
        public DateTime LastDate { get; set; }
        public int FirstUser { get; set; }
        public int LastUser { get; set; }
        public string CodiceEsterno { get; set; }

        public virtual ICollection<PurchaseOrder> PurchaseOrder { get; set; }
        public virtual ICollection<Receiving> Receiving { get; set; }
        public virtual ICollection<SalesOrder> SalesOrder { get; set; }
        public virtual ICollection<Shipment> Shipment { get; set; }
    }
}