// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class Documenti
    {
        public string DocumentiId { get; set; }
        public string DocumentiNome { get; set; }
        public byte[] Contenuto { get; set; }
        public string ReceivingId { get; set; }
        public bool Valido { get; set; }
        public DateTime FirstDate { get; set; }
        public DateTime LastDate { get; set; }
        public int FirstUser { get; set; }
        public int LastUser { get; set; }

        public virtual Receiving Receiving { get; set; }
    }
}