// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class Matricole
    {
        public Matricole()
        {
            MatricoleScarico = new HashSet<MatricoleScarico>();
            MatricoleStoricoTrasferimenti = new HashSet<MatricoleStoricoTrasferimenti>();
        }

        public string MatricoleId { get; set; }
        public string Matricola { get; set; }
        public string ReceivingLineId { get; set; }
        public decimal IdProdotto { get; set; }
        public string CodCostruttore { get; set; }
        public string WarehouseId { get; set; }
        public string Cespite { get; set; }
        public bool Uscita { get; set; }
        public bool Trasferita { get; set; }
        public string ShipmentId { get; set; }
        public string ShipmentLineId { get; set; }

        public virtual ReceivingLine ReceivingLine { get; set; }
        public virtual ICollection<MatricoleScarico> MatricoleScarico { get; set; }
        public virtual ICollection<MatricoleStoricoTrasferimenti> MatricoleStoricoTrasferimenti { get; set; }
    }
}