// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class MatricoleScarico
    {
        public string MatricoleScaricoId { get; set; }
        public string Matricola { get; set; }
        public string ShipmentLineId { get; set; }
        public decimal IdProdotto { get; set; }
        public string CodCostruttore { get; set; }
        public string MatricoleId { get; set; }

        public virtual Matricole Matricole { get; set; }
        public virtual ShipmentLine ShipmentLine { get; set; }
    }
}