// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            PurchaseOrderLine = new HashSet<PurchaseOrderLine>();
            PurchaseOrderReceiving = new HashSet<PurchaseOrderReceiving>();
        }

        public string PurchaseOrderId { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public DateTime PurchaseOrderDate { get; set; }
        public DateTime ReceiveDate { get; set; }
        public string ReferenceNumberInternal { get; set; }
        public string ReferenceNumberExternal { get; set; }
        public string PurchaseOrderDescription { get; set; }
        public decimal? IdUbicazione { get; set; }
        public long IdFornitore { get; set; }
        public string ManagerInternal { get; set; }
        public string ManagerVendor { get; set; }
        public int PurchaseOrderStatus { get; set; }
        public string CausaleMovimentiMagazzinoId { get; set; }
        public bool Valido { get; set; }
        public DateTime FirstDate { get; set; }
        public DateTime LastDate { get; set; }
        public int FirstUser { get; set; }
        public int LastUser { get; set; }
        public string CodiceCommessa { get; set; }
        public string CodiceEsterno { get; set; }

        public virtual CausaleMovimentiMagazzino CausaleMovimentiMagazzino { get; set; }
        public virtual ICollection<PurchaseOrderLine> PurchaseOrderLine { get; set; }
        public virtual ICollection<PurchaseOrderReceiving> PurchaseOrderReceiving { get; set; }
    }
}