// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class PurchaseOrderLine
    {
        public PurchaseOrderLine()
        {
            PurchaseOrderReceiving = new HashSet<PurchaseOrderReceiving>();
        }

        public string PurchaseOrderLineId { get; set; }
        public string PurchaseOrderId { get; set; }
        public decimal IdProdotto { get; set; }
        public int Qty { get; set; }
        public bool Valido { get; set; }
        public DateTime FirstDate { get; set; }
        public DateTime LastDate { get; set; }
        public int FirstUser { get; set; }
        public int LastUser { get; set; }
        public string ReceivingNumber { get; set; }

        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual ICollection<PurchaseOrderReceiving> PurchaseOrderReceiving { get; set; }
    }
}