// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class ReceivingLine
    {
        public ReceivingLine()
        {
            Matricole = new HashSet<Matricole>();
            PurchaseOrderReceiving = new HashSet<PurchaseOrderReceiving>();
        }

        public string ReceivingLineId { get; set; }
        public string ReceivingId { get; set; }
        public string WarehouseId { get; set; }
        public decimal IdProdotto { get; set; }
        public int Qty { get; set; }
        public int QtyReceive { get; set; }
        public int QtyReceived { get; set; }
        public bool RigaCompleta { get; set; }
        public bool Valido { get; set; }
        public DateTime FirstDate { get; set; }
        public DateTime LastDate { get; set; }
        public int FirstUser { get; set; }
        public int LastUser { get; set; }

        public virtual Receiving Receiving { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual ICollection<Matricole> Matricole { get; set; }
        public virtual ICollection<PurchaseOrderReceiving> PurchaseOrderReceiving { get; set; }
    }
}