// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class Receiving
    {
        public Receiving()
        {
            Documenti = new HashSet<Documenti>();
            PurchaseOrderReceiving = new HashSet<PurchaseOrderReceiving>();
            ReceivingLine = new HashSet<ReceivingLine>();
        }

        public string ReceivingId { get; set; }
        public string PurchaseOrderId { get; set; }
        public string ReceivingNumber { get; set; }
        public DateTime ReceivingDate { get; set; }
        public long IdFornitore { get; set; }
        public string RiferimentiDdt { get; set; }
        public string WarehouseId { get; set; }
        public string CausaleMovimentiMagazzinoId { get; set; }
        public bool Completato { get; set; }
        public decimal IdUbicazione { get; set; }
        public string AspettoBeni { get; set; }
        public bool Valido { get; set; }
        public DateTime FirstDate { get; set; }
        public DateTime LastDate { get; set; }
        public int FirstUser { get; set; }
        public int LastUser { get; set; }
        public DateTime DataDdtfornitore { get; set; }

        public virtual CausaleMovimentiMagazzino CausaleMovimentiMagazzino { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual ICollection<Documenti> Documenti { get; set; }
        public virtual ICollection<PurchaseOrderReceiving> PurchaseOrderReceiving { get; set; }
        public virtual ICollection<ReceivingLine> ReceivingLine { get; set; }
    }
}