// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class SalesOrder
    {
        public SalesOrder()
        {
            SalesOrderLine = new HashSet<SalesOrderLine>();
            SalesOrderShipment = new HashSet<SalesOrderShipment>();
        }

        public string SalesOrderId { get; set; }
        public string SalesOrderNumber { get; set; }
        public DateTime SalesOrderDate { get; set; }
        public DateTime DeliveryDate { get; set; }
        public string ReferenceNumberInternal { get; set; }
        public string ReferenceNumberExternal { get; set; }
        public string Description { get; set; }
        public string ManagerInternal { get; set; }
        public int SalesOrderStatus { get; set; }
        public string CausaleMovimentiMagazzinoId { get; set; }
        public decimal IdUbicazione { get; set; }
        public bool Valido { get; set; }
        public DateTime FirstDate { get; set; }
        public DateTime LastDate { get; set; }
        public int FirstUser { get; set; }
        public int LastUser { get; set; }
        public string IncotermsId { get; set; }
        public string CodiceCommessa { get; set; }
        public string CodiceEsterno { get; set; }

        public virtual CausaleMovimentiMagazzino CausaleMovimentiMagazzino { get; set; }
        public virtual Incoterms Incoterms { get; set; }
        public virtual ICollection<SalesOrderLine> SalesOrderLine { get; set; }
        public virtual ICollection<SalesOrderShipment> SalesOrderShipment { get; set; }
    }
}