// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class SalesOrderShipment
    {
        public string Id { get; set; }
        public string SalesOrderId { get; set; }
        public string ShipmentId { get; set; }
        public int QtySent { get; set; }
        public string SalesOrderLineId { get; set; }
        public string ShipmentLineId { get; set; }
        public int QtyTot { get; set; }

        public virtual SalesOrder SalesOrder { get; set; }
        public virtual SalesOrderLine SalesOrderLine { get; set; }
        public virtual Shipment Shipment { get; set; }
        public virtual ShipmentLine ShipmentLine { get; set; }
    }
}