// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class SalesOrderLine
    {
        public SalesOrderLine()
        {
            SalesOrderShipment = new HashSet<SalesOrderShipment>();
        }

        public string SalesOrderLineId { get; set; }
        public string SalesOrderId { get; set; }
        public decimal IdProdotto { get; set; }
        public int Qty { get; set; }
        public bool Valido { get; set; }
        public DateTime FirstDate { get; set; }
        public DateTime LastDate { get; set; }
        public int FirstUser { get; set; }
        public int LastUser { get; set; }
        public string ShipmentNumber { get; set; }

        public virtual SalesOrder SalesOrder { get; set; }
        public virtual ICollection<SalesOrderShipment> SalesOrderShipment { get; set; }
    }
}