// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class ShipmentLine
    {
        public ShipmentLine()
        {
            MatricoleScarico = new HashSet<MatricoleScarico>();
            SalesOrderShipment = new HashSet<SalesOrderShipment>();
        }

        public string ShipmentLineId { get; set; }
        public string ShipmentId { get; set; }
        public string WarehouseId { get; set; }
        public decimal IdProdotto { get; set; }
        public int Qty { get; set; }
        public int QtyShipment { get; set; }
        public int QtyShipped { get; set; }
        public bool RigaCompleta { get; set; }
        public string Asset { get; set; }
        public bool Valido { get; set; }
        public DateTime FirstDate { get; set; }
        public DateTime LastDate { get; set; }
        public int FirstUser { get; set; }
        public int LastUser { get; set; }

        public virtual Shipment Shipment { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual ICollection<MatricoleScarico> MatricoleScarico { get; set; }
        public virtual ICollection<SalesOrderShipment> SalesOrderShipment { get; set; }
    }
}