// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class TransferOrder
    {
        public TransferOrder()
        {
            MatricoleStoricoTrasferimenti = new HashSet<MatricoleStoricoTrasferimenti>();
            TransferOrderLine = new HashSet<TransferOrderLine>();
        }

        public string TransferOrderId { get; set; }
        public string TransferOrderNumber { get; set; }
        public DateTime TransferOrderDate { get; set; }
        public string Description { get; set; }
        public string WarehouseFromId { get; set; }
        public string WarehouseToId { get; set; }
        public bool Valido { get; set; }
        public DateTime FirstDate { get; set; }
        public DateTime LastDate { get; set; }
        public int FirstUser { get; set; }
        public int LastUser { get; set; }

        public virtual Warehouse WarehouseFrom { get; set; }
        public virtual Warehouse WarehouseTo { get; set; }
        public virtual ICollection<MatricoleStoricoTrasferimenti> MatricoleStoricoTrasferimenti { get; set; }
        public virtual ICollection<TransferOrderLine> TransferOrderLine { get; set; }
    }
}