// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class Vmstock
    {
        public string VmstockId { get; set; }
        public decimal IdProdotto { get; set; }
        public string WarehouseId { get; set; }
        public int QtyReceiving { get; set; }
        public int QtyShipment { get; set; }
        public int QtyOnHand { get; set; }
        public int QtyTransferIn { get; set; }
        public int QtyTransferOut { get; set; }
    }
}