// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class VwDatiRichiestaDelivery
    {
        public string CodiceChiamata { get; set; }
        public decimal IdEvento { get; set; }
        public DateTime? DataAttivita { get; set; }
        public string DescrizioneProdotto { get; set; }
        public string Matricola { get; set; }
        public string Matricola2 { get; set; }
        public string Note { get; set; }
        public string Contatto { get; set; }
        public string EmailContatto { get; set; }
        public string Telefono { get; set; }
        public string Asset { get; set; }
    }
}