// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class VwFornitoriUbicazioni
    {
        public long IdFornitoreUbicazione { get; set; }
        public long? IdFornitore { get; set; }
        public string CodiceEsterno { get; set; }
        public string CodFornitore { get; set; }
        public string RagioneSociale { get; set; }
        public string Indirizzo { get; set; }
        public string Localita { get; set; }
        public string Provincia { get; set; }
        public string Cap { get; set; }
        public string RagioneSocialeFornitore { get; set; }
        public bool Valido { get; set; }
    }
}