// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class VwGiacenza
    {
        public string GiacenzaId { get; set; }
        public decimal IdProdotto { get; set; }
        public string TipoProd { get; set; }
        public string DescrizioneProd { get; set; }
        public string DescrizioneCostr { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseName { get; set; }
        public decimal? IdUbicazione { get; set; }
        public string RagioneSocialeUbic { get; set; }
        public decimal? IdCliente { get; set; }
        public string RagionesocialeCliente { get; set; }
        public int QtyReceiving { get; set; }
        public int QtyShipment { get; set; }
        public int QtyTransferIn { get; set; }
        public int QtyTransferOut { get; set; }
        public int QtyOnHand { get; set; }
    }
}