// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class VwProdottiOrdine
    {
        public string OrderId { get; set; }
        public string OrderLineId { get; set; }
        public decimal? IdProdotto { get; set; }
        public string CodCostruttore { get; set; }
        public string Costruttore { get; set; }
        public string CategoriaMerci { get; set; }
        public string Modello { get; set; }
        public string Tipo { get; set; }
        public string Descrizione { get; set; }
        public int Qty { get; set; }
        public int Acquisto { get; set; }
        public int Vendita { get; set; }
        public int QtyReceived { get; set; }
        public int QtyShipped { get; set; }
    }
}