// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class VwProdottiTrasferiti
    {
        public string TransferOrderId { get; set; }
        public string TransferOrderLineId { get; set; }
        public string WarehouseFromId { get; set; }
        public string WarehouseToId { get; set; }
        public decimal? IdProdotto { get; set; }
        public string CodCostruttore { get; set; }
        public string Costruttore { get; set; }
        public string CategoriaMerci { get; set; }
        public string Modello { get; set; }
        public string Tipo { get; set; }
        public string Descrizione { get; set; }
        public bool? RichiedeMatricola { get; set; }
        public int Qty { get; set; }
    }
}