// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class VwResponsabili
    {
        public decimal IdResponsabili { get; set; }
        public string CodRisorsa { get; set; }
        public string Nome { get; set; }
        public string DescStat { get; set; }
        public string Indirizzo { get; set; }
        public string Localita { get; set; }
        public string Provincia { get; set; }
        public string Cap { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Cellulare { get; set; }
        public string Email { get; set; }
        public bool? Valido { get; set; }
    }
}