// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class VwUbicazioni
    {
        public decimal IdUbicazione { get; set; }
        public decimal? IdCliente { get; set; }
        public string RagioneSociale { get; set; }
        public string Indirizzo { get; set; }
        public string Localita { get; set; }
        public string Provincia { get; set; }
        public string Cap { get; set; }
        public string RagioneSocialeCliente { get; set; }
        public bool Valido { get; set; }
    }
}