// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PortingMagazzino.Data.Models
{
    public partial class Warehouse
    {
        public Warehouse()
        {
            MatricoleStoricoTrasferimentiWarehouseFrom = new HashSet<MatricoleStoricoTrasferimenti>();
            MatricoleStoricoTrasferimentiWarehouseTo = new HashSet<MatricoleStoricoTrasferimenti>();
            Receiving = new HashSet<Receiving>();
            ReceivingLine = new HashSet<ReceivingLine>();
            ShipmentLine = new HashSet<ShipmentLine>();
            TransferOrderWarehouseFrom = new HashSet<TransferOrder>();
            TransferOrderWarehouseTo = new HashSet<TransferOrder>();
        }

        public string WarehouseId { get; set; }
        public string WarehouseName { get; set; }
        public string Description { get; set; }
        public string Indirizzo { get; set; }
        public string Provincia { get; set; }
        public string Citta { get; set; }
        public string CodiceEsterno { get; set; }
        public decimal IdUbicazione { get; set; }
        public bool Valido { get; set; }
        public DateTime FirstDate { get; set; }
        public DateTime LastDate { get; set; }
        public int FirstUser { get; set; }
        public int LastUser { get; set; }
        public string Cap { get; set; }

        public virtual ICollection<MatricoleStoricoTrasferimenti> MatricoleStoricoTrasferimentiWarehouseFrom { get; set; }
        public virtual ICollection<MatricoleStoricoTrasferimenti> MatricoleStoricoTrasferimentiWarehouseTo { get; set; }
        public virtual ICollection<Receiving> Receiving { get; set; }
        public virtual ICollection<ReceivingLine> ReceivingLine { get; set; }
        public virtual ICollection<ShipmentLine> ShipmentLine { get; set; }
        public virtual ICollection<TransferOrder> TransferOrderWarehouseFrom { get; set; }
        public virtual ICollection<TransferOrder> TransferOrderWarehouseTo { get; set; }
    }
}